# Paths
log_path: '/local/home/bjbraun/Projects/egoEMOTION/runs'
pretrained_model_path: '/local/home/bjbraun/Projects/egoEMOTION/pretrained_models'

# Training options
mode: 'train_and_test'  # 'train_and_test' or 'only_test'
device: 'cuda:7'  # 'cuda:X' or 'cpu'
name_extension: ''
num_epochs: 20
batch_size: 128
lr: 0.0001
best_epoch: Null

# Optimizer options
optim: 'adam'  # adam or sgd
momentum: 0.9
weight_decay: 0.0000005

# Model options
tcn_nfilters: [16, 16]
tcn_kernel_size: 6
tcn_dropout: 0.2
trans_d_model: 128
trans_n_heads: 4
trans_num_layers: 1
trans_dim_feedforward: 128
shared_embed_dim: 64
trans_dropout: 0.2
trans_activation: 'relu'
trans_norm: 'LayerNorm'
sl_embed_dim1: 128
sl_embed_dim2: 64
sl_activation: 'relu'
sl_dropout: 0.2
